# Generated by Django 5.2.18 on 2026-10-08 12:30

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="Jonas Dülberg", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Outdoor- und Werbefotografie",
                        max_length=150,
                        verbose_name="Untertitel",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name / Firma"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Straße und Hausnummer"
                    ),
                ),
                (
                    "postal_code_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="PLZ und Ort"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "legal_link_text",
                    models.CharField(
                        default="Impressum / Datenschutz",
                        max_length=100,
                        verbose_name="Linktext",
                    ),
                ),
                (
                    "footer_download_text",
                    models.CharField(
                        blank=True,
                        help_text='Zum Beispiel: Handy-Wallpaper "Waves" (kostenlos)',
                        max_length=150,
                        verbose_name="Text zum Download",
                    ),
                ),
                (
                    "footer_download",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Datei",
                    ),
                ),
                (
                    "legal_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Seite für Impressum / Datenschutz",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kopf- und Fußzeile",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Zum Beispiel: Instagram",
                        max_length=50,
                        verbose_name="Bezeichnung",
                    ),
                ),
                ("url", models.URLField(verbose_name="Adresse")),
                (
                    "settings",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="core.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social-Media-Link",
                "verbose_name_plural": "Social-Media-Links",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
