# Generated by Django 5.2.18 on 2026-10-10 12:15

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_custom_image"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Einleitung"),
                ),
                (
                    "contact_heading",
                    models.CharField(
                        default="Kontakt",
                        max_length=80,
                        verbose_name="Überschrift Kontakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking-Seite",
                "verbose_name_plural": "Booking-Seiten",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="GalleryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Einleitung"),
                ),
            ],
            options={
                "verbose_name": "Galerie-Seite",
                "verbose_name_plural": "Galerie-Seiten",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True, verbose_name="Text")),
            ],
            options={
                "verbose_name": "Textseite",
                "verbose_name_plural": "Textseiten",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True, verbose_name="Text")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.customimage",
                        verbose_name="Porträt",
                    ),
                ),
            ],
            options={
                "verbose_name": "About-Seite",
                "verbose_name_plural": "About-Seiten",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BookingStripImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.customimage",
                        verbose_name="Bild",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strip_images",
                        to="pages.bookingpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GallerySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Überschrift"
                    ),
                ),
                ("text", wagtail.fields.RichTextField(blank=True, verbose_name="Text")),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("grid", "Raster (ganze Bilder, gleich hohe Zeilen)"),
                            (
                                "strip_large",
                                "Bildreihe zum Blättern, groß (Hochformat-Ausschnitte)",
                            ),
                            (
                                "strip_small",
                                "Bildreihe zum Blättern, klein (Hochformat-Ausschnitte)",
                            ),
                        ],
                        default="grid",
                        max_length=20,
                        verbose_name="Darstellung",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="pages.gallerypage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abschnitt",
                "verbose_name_plural": "Abschnitte",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GallerySectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.customimage",
                        verbose_name="Bild",
                    ),
                ),
                (
                    "section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pages.gallerysection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GallerySectionVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="pages.gallerysection",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Video (MP4)",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
